apiVersion: v1
kind: Pod
metadata:
  name: bar
spec:
  containers:
    - name: foo
      image: docker/testimg:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: ENV_NAME
          value: test2d3
      dockerLogDriver: json-file
      dockerLogOptions:
        - name: max-size
          value: 1k
        - name: max-file
          value: "5"
      ports:
      - containerPort: 8080
